// FILE: src/components/matu/TicketScanner.tsx
// A camera-based QR scanner for drivers/conductors. Reads MATU-TICKET:<booking_id> codes
// generated by the passenger's ticket screen, looks the booking up, and lets the driver
// mark it "boarded" with one tap. Restricted to bookings on the driver's own active trip.
import { useEffect, useRef, useState } from "react";
import jsQR from "jsqr";
import { CheckCircle2, Loader2, ScanLine, X, XCircle } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";

type ScanResult =
  | { kind: "idle" }
  | { kind: "checking" }
  | {
      kind: "found";
      bookingId: string;
      seatNumber: number | null;
      status: string;
      alreadyBoarded: boolean;
    }
  | { kind: "not_found" }
  | { kind: "wrong_trip" };

export function TicketScanner({ tripId, onBoarded }: { tripId: string; onBoarded: () => void }) {
  const [open, setOpen] = useState(false);
  const [result, setResult] = useState<ScanResult>({ kind: "idle" });
  const [marking, setMarking] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const rafRef = useRef<number | null>(null);
  const lastScannedRef = useRef<string | null>(null);

  useEffect(() => {
    if (!open) return;

    let cancelled = false;

    async function startCamera() {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({
          video: { facingMode: "environment" },
        });
        if (cancelled) {
          stream.getTracks().forEach((t) => t.stop());
          return;
        }
        streamRef.current = stream;
        if (videoRef.current) {
          videoRef.current.srcObject = stream;
          await videoRef.current.play();
        }
        tick();
      } catch {
        toast.error("Couldn't access camera. Check camera permissions and try again.");
        setOpen(false);
      }
    }

    function tick() {
      const video = videoRef.current;
      const canvas = canvasRef.current;
      if (!video || !canvas || video.readyState !== video.HAVE_ENOUGH_DATA) {
        rafRef.current = requestAnimationFrame(tick);
        return;
      }
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      const ctx = canvas.getContext("2d", { willReadFrequently: true });
      if (!ctx) {
        rafRef.current = requestAnimationFrame(tick);
        return;
      }
      ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
      const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
      const code = jsQR(imageData.data, imageData.width, imageData.height, {
        inversionAttempts: "dontInvert",
      });
      if (code && code.data && code.data !== lastScannedRef.current) {
        lastScannedRef.current = code.data;
        handleScanned(code.data);
        return; // stop the loop until the driver dismisses this result
      }
      rafRef.current = requestAnimationFrame(tick);
    }

    startCamera();

    return () => {
      cancelled = true;
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
      streamRef.current?.getTracks().forEach((t) => t.stop());
      streamRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  async function handleScanned(payload: string) {
    const prefix = "MATU-TICKET:";
    if (!payload.startsWith(prefix)) {
      setResult({ kind: "not_found" });
      return;
    }
    const bookingId = payload.slice(prefix.length).trim();
    setResult({ kind: "checking" });
    const { data, error } = await supabase
      .from("bookings")
      .select("id,trip_id,seat_number,status")
      .eq("id", bookingId)
      .maybeSingle();
    if (error || !data) {
      setResult({ kind: "not_found" });
      return;
    }
    if (data.trip_id !== tripId) {
      setResult({ kind: "wrong_trip" });
      return;
    }
    setResult({
      kind: "found",
      bookingId: data.id,
      seatNumber: data.seat_number,
      status: data.status,
      alreadyBoarded: data.status === "boarded",
    });
  }

  async function markBoarded(bookingId: string) {
    setMarking(true);
    const { error } = await supabase
      .from("bookings")
      .update({ status: "boarded" })
      .eq("id", bookingId);
    setMarking(false);
    if (error) return toast.error(error.message || "Could not update booking");
    toast.success("Passenger marked as boarded");
    onBoarded();
    resumeScanning();
  }

  function resumeScanning() {
    lastScannedRef.current = null;
    setResult({ kind: "idle" });
    rafRef.current = requestAnimationFrame(function loop() {
      const video = videoRef.current;
      const canvas = canvasRef.current;
      if (!video || !canvas || video.readyState !== video.HAVE_ENOUGH_DATA) {
        rafRef.current = requestAnimationFrame(loop);
        return;
      }
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      const ctx = canvas.getContext("2d", { willReadFrequently: true });
      if (!ctx) {
        rafRef.current = requestAnimationFrame(loop);
        return;
      }
      ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
      const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
      const code = jsQR(imageData.data, imageData.width, imageData.height, {
        inversionAttempts: "dontInvert",
      });
      if (code && code.data && code.data !== lastScannedRef.current) {
        lastScannedRef.current = code.data;
        handleScanned(code.data);
        return;
      }
      rafRef.current = requestAnimationFrame(loop);
    });
  }

  function close() {
    setOpen(false);
    setResult({ kind: "idle" });
    lastScannedRef.current = null;
  }

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="inline-flex w-full items-center justify-center gap-2 rounded-md border border-border px-3 py-2 text-sm font-medium"
      >
        <ScanLine className="size-4" /> Scan ticket
      </button>

      {open && (
        <div className="fixed inset-0 z-50 flex flex-col bg-black">
          <div className="flex items-center justify-between p-4 text-white">
            <span className="text-sm font-medium">Scan passenger ticket</span>
            <button onClick={close} className="rounded-md p-1 hover:bg-white/10">
              <X className="size-5" />
            </button>
          </div>

          <div className="relative flex-1">
            <video ref={videoRef} playsInline muted className="h-full w-full object-cover" />
            <canvas ref={canvasRef} className="hidden" />
            {result.kind === "idle" && (
              <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
                <div className="size-56 rounded-2xl border-2 border-white/70" />
              </div>
            )}
          </div>

          {result.kind !== "idle" && (
            <div className="border-t border-white/10 bg-background p-5">
              {result.kind === "checking" && (
                <div className="flex items-center justify-center gap-2 py-4 text-sm text-muted-foreground">
                  <Loader2 className="size-4 animate-spin" /> Checking ticket…
                </div>
              )}
              {result.kind === "not_found" && (
                <div className="grid gap-3">
                  <div className="flex items-center gap-2 text-destructive">
                    <XCircle className="size-5" />
                    <span className="text-sm font-medium">Not a valid Matu ticket</span>
                  </div>
                  <button
                    onClick={resumeScanning}
                    className="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground"
                  >
                    Scan again
                  </button>
                </div>
              )}
              {result.kind === "wrong_trip" && (
                <div className="grid gap-3">
                  <div className="flex items-center gap-2 text-destructive">
                    <XCircle className="size-5" />
                    <span className="text-sm font-medium">This ticket is for a different trip</span>
                  </div>
                  <button
                    onClick={resumeScanning}
                    className="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground"
                  >
                    Scan again
                  </button>
                </div>
              )}
              {result.kind === "found" && (
                <div className="grid gap-3">
                  <div className="flex items-center gap-2 text-primary">
                    <CheckCircle2 className="size-5" />
                    <span className="text-sm font-medium">
                      {result.alreadyBoarded ? "Already boarded" : "Valid ticket"}
                    </span>
                  </div>
                  <div className="text-sm text-muted-foreground">
                    Seat {result.seatNumber ?? "—"} · Ticket{" "}
                    {result.bookingId.slice(0, 8).toUpperCase()}
                  </div>
                  {result.alreadyBoarded ? (
                    <button
                      onClick={resumeScanning}
                      className="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground"
                    >
                      Scan next passenger
                    </button>
                  ) : (
                    <div className="flex gap-2">
                      <button
                        onClick={() => markBoarded(result.bookingId)}
                        disabled={marking}
                        className="flex-1 rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground disabled:opacity-60"
                      >
                        {marking ? "Marking…" : "Mark as boarded"}
                      </button>
                      <button
                        onClick={resumeScanning}
                        className="rounded-md border border-border px-3 py-2 text-sm"
                      >
                        Skip
                      </button>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </>
  );
}
