/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRideIndexRouteImport } from './routes/_authenticated/ride.index'
import { Route as AuthenticatedFleetIndexRouteImport } from './routes/_authenticated/fleet.index'
import { Route as AuthenticatedDriveIndexRouteImport } from './routes/_authenticated/drive.index'
import { Route as AuthenticatedRideHistoryRouteImport } from './routes/_authenticated/ride.history'
import { Route as AuthenticatedRideRouteIdRouteImport } from './routes/_authenticated/ride.$routeId'
import { Route as AuthenticatedFleetSaccoIdRouteImport } from './routes/_authenticated/fleet.$saccoId'
import { Route as AuthenticatedDriveTripRouteImport } from './routes/_authenticated/drive.trip'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRideIndexRoute = AuthenticatedRideIndexRouteImport.update({
  id: '/ride/',
  path: '/ride/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetIndexRoute = AuthenticatedFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriveIndexRoute = AuthenticatedDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRideHistoryRoute =
  AuthenticatedRideHistoryRouteImport.update({
    id: '/ride/history',
    path: '/ride/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRideRouteIdRoute =
  AuthenticatedRideRouteIdRouteImport.update({
    id: '/ride/$routeId',
    path: '/ride/$routeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFleetSaccoIdRoute =
  AuthenticatedFleetSaccoIdRouteImport.update({
    id: '/fleet/$saccoId',
    path: '/fleet/$saccoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriveTripRoute = AuthenticatedDriveTripRouteImport.update({
  id: '/drive/trip',
  path: '/drive/trip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/drive/trip': typeof AuthenticatedDriveTripRoute
  '/fleet/$saccoId': typeof AuthenticatedFleetSaccoIdRoute
  '/ride/$routeId': typeof AuthenticatedRideRouteIdRoute
  '/ride/history': typeof AuthenticatedRideHistoryRoute
  '/drive/': typeof AuthenticatedDriveIndexRoute
  '/fleet/': typeof AuthenticatedFleetIndexRoute
  '/ride/': typeof AuthenticatedRideIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/drive/trip': typeof AuthenticatedDriveTripRoute
  '/fleet/$saccoId': typeof AuthenticatedFleetSaccoIdRoute
  '/ride/$routeId': typeof AuthenticatedRideRouteIdRoute
  '/ride/history': typeof AuthenticatedRideHistoryRoute
  '/drive': typeof AuthenticatedDriveIndexRoute
  '/fleet': typeof AuthenticatedFleetIndexRoute
  '/ride': typeof AuthenticatedRideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/drive/trip': typeof AuthenticatedDriveTripRoute
  '/_authenticated/fleet/$saccoId': typeof AuthenticatedFleetSaccoIdRoute
  '/_authenticated/ride/$routeId': typeof AuthenticatedRideRouteIdRoute
  '/_authenticated/ride/history': typeof AuthenticatedRideHistoryRoute
  '/_authenticated/drive/': typeof AuthenticatedDriveIndexRoute
  '/_authenticated/fleet/': typeof AuthenticatedFleetIndexRoute
  '/_authenticated/ride/': typeof AuthenticatedRideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/drive/trip'
    | '/fleet/$saccoId'
    | '/ride/$routeId'
    | '/ride/history'
    | '/drive/'
    | '/fleet/'
    | '/ride/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/drive/trip'
    | '/fleet/$saccoId'
    | '/ride/$routeId'
    | '/ride/history'
    | '/drive'
    | '/fleet'
    | '/ride'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/drive/trip'
    | '/_authenticated/fleet/$saccoId'
    | '/_authenticated/ride/$routeId'
    | '/_authenticated/ride/history'
    | '/_authenticated/drive/'
    | '/_authenticated/fleet/'
    | '/_authenticated/ride/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ride/': {
      id: '/_authenticated/ride/'
      path: '/ride'
      fullPath: '/ride/'
      preLoaderRoute: typeof AuthenticatedRideIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet/': {
      id: '/_authenticated/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof AuthenticatedFleetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive/': {
      id: '/_authenticated/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof AuthenticatedDriveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ride/history': {
      id: '/_authenticated/ride/history'
      path: '/ride/history'
      fullPath: '/ride/history'
      preLoaderRoute: typeof AuthenticatedRideHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ride/$routeId': {
      id: '/_authenticated/ride/$routeId'
      path: '/ride/$routeId'
      fullPath: '/ride/$routeId'
      preLoaderRoute: typeof AuthenticatedRideRouteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet/$saccoId': {
      id: '/_authenticated/fleet/$saccoId'
      path: '/fleet/$saccoId'
      fullPath: '/fleet/$saccoId'
      preLoaderRoute: typeof AuthenticatedFleetSaccoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drive/trip': {
      id: '/_authenticated/drive/trip'
      path: '/drive/trip'
      fullPath: '/drive/trip'
      preLoaderRoute: typeof AuthenticatedDriveTripRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDriveTripRoute: typeof AuthenticatedDriveTripRoute
  AuthenticatedFleetSaccoIdRoute: typeof AuthenticatedFleetSaccoIdRoute
  AuthenticatedRideRouteIdRoute: typeof AuthenticatedRideRouteIdRoute
  AuthenticatedRideHistoryRoute: typeof AuthenticatedRideHistoryRoute
  AuthenticatedDriveIndexRoute: typeof AuthenticatedDriveIndexRoute
  AuthenticatedFleetIndexRoute: typeof AuthenticatedFleetIndexRoute
  AuthenticatedRideIndexRoute: typeof AuthenticatedRideIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDriveTripRoute: AuthenticatedDriveTripRoute,
  AuthenticatedFleetSaccoIdRoute: AuthenticatedFleetSaccoIdRoute,
  AuthenticatedRideRouteIdRoute: AuthenticatedRideRouteIdRoute,
  AuthenticatedRideHistoryRoute: AuthenticatedRideHistoryRoute,
  AuthenticatedDriveIndexRoute: AuthenticatedDriveIndexRoute,
  AuthenticatedFleetIndexRoute: AuthenticatedFleetIndexRoute,
  AuthenticatedRideIndexRoute: AuthenticatedRideIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
